### ISSUE TITLE
Right-eye buffer rendering blue clear command for camera background in editor

### ISSUE THREAD

**Issue by talothman** [jorgejgnz/HPTK-Sample#2] opened 2020-10-22 16:06 UTC
![vlcsnap-2020-10-22-12h05m56s799](https://user-images.githubusercontent.com/5286101/96899543-0992db00-145f-11eb-8bb2-690c5b90e616.png)

**Comment by jorgejgnz** [comment] 2020-10-26 08:19
Hi Talal, thanks for writing up this issue!

How can this problem be reproduced?

**Comment by shinkaze33** [comment] 2020-11-04 23:04
Hey @jorgejgnz I just reproduced this in Unity 2019.4 in a new project?
The background skybox, hand and object grab edge shaders are appearing in one eye but not the other.

**Comment by shinkaze33** [comment] 2020-11-05 21:21
Update: Researched this, and it appears to be an issue with the ToonBasicOutline.shader not being compatible with  Single Pass Instanced Rendering.  [Here is an Unity forum post from someone with a similar issue plus a resolution](https://forum.unity.com/threads/using-xr-management-package-renders-to-one-eye-only.823113/).

**Comment by shinkaze33** [comment] 2020-11-05 23:08
> Hi Talal, thanks for writing up this issue!
> 
> How can this problem be reproduced?

@jorgejgnz I was able to reproduce in 2019.4 with a fresh project

The reason this is occurring is because the [Edge Shader is not compatible with the URP Single Pass Instanced Mode](https://forum.unity.com/threads/using-xr-management-package-renders-to-one-eye-only.823113/).

The Solution is:
1.) change the Build Platform from PC to Android
2.) Change Render mode to Multipass, 

Then the edge shader will work normally.

You do not have to change the shader, but you may want to update the installation instructions to say the shader will not work in single pass instanced which is the default Oculus PC render mode folks will be in if they download your repo on a fresh build.

**Comment by jorgejgnz** [comment] 2020-11-22 17:22
@shinkaze33 Thank you so much for you detailed response!

I've included a note for this problem in the [Getting-started guide](https://github.com/jorgejgnz/HPTK/wiki/Getting-started)

**Closed as completed** 2020-11-22 17:22 UTC
